### ISSUE TITLE
Build of Screen Fails

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/homebrew-dupes#63]
The gist-logs are here: https://gist.github.com/jwhite007/83c8480a648c4dececf89da886c3f450

**Comment by rwhogg** [comment]
Error is (https://gist.github.com/jwhite007/83c8480a648c4dececf89da886c3f450#file-03-make-L33-L41):

```
utmp.c: In function 'xpututline':
utmp.c:889:13: error: dereferencing pointer to incomplete type 'struct utmp'
     return u->ut_type == DEAD_PROCESS ? u : 0;
             ^
utmp.c:889:26: error: 'DEAD_PROCESS' undeclared (first use in this function)
     return u->ut_type == DEAD_PROCESS ? u : 0;
                          ^
utmp.c:889:26: note: each undeclared identifier is reported only once for each function it appears in
make: *** [utmp.o] Error 1
```

**Comment by rwhogg** [comment]
This looks like the same error @sjackman got [here](https://github.com/Linuxbrew/homebrew-dupes/pull/32#issuecomment-221784770).

It's closely related to an upstream bug - see https://savannah.gnu.org/bugs/?28139

**Comment by rwhogg** [comment]
@jwhite007 can you do a `brew update` and then retry the build please? It was recently fixed by #68.

**Comment by jwhite007** [comment]
@rwhogg, screen installed just fine after the update. Thanks for your help.

**Comment by rwhogg** [comment]
Happy to help @jwhite007!
